import { useState } from "react";
import { Button } from "../../../shared/components/ui/Button";
import { FormField } from "../../../shared/components/ui/FormField";
import type { PricingInput, QuoteItem } from "../types/quote.types";
interface Props { items: readonly QuoteItem[]; discountAmount: number; taxRate: number; isSaving: boolean; onSave: (input: PricingInput) => Promise<void>; }
export function QuotePricingEditor({ items, discountAmount, taxRate, isSaving, onSave }: Props) {
    const [values, setValues] = useState(() => items.map((item) => ({ itemId: item.id, unitPrice: String(item.unitPrice ?? ""), discountAmount: String(item.discountAmount ?? 0) })));
    const [generalDiscount, setGeneralDiscount] = useState(String(discountAmount)); const [tax, setTax] = useState(String(taxRate));
    return <section className="quote-panel quote-editor"><h2>Pricing</h2>{values.map((value, index) => <div className="quote-price-row" key={value.itemId}><strong>{items[index].productName}</strong><FormField label="Precio unitario" htmlFor={`unit-price-${value.itemId}`}><input className="form-control" id={`unit-price-${value.itemId}`} type="number" min={0} step="0.01" value={value.unitPrice} onChange={(event) => setValues((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, unitPrice: event.target.value } : item))} disabled={isSaving} /></FormField><FormField label="Descuento" htmlFor={`item-discount-${value.itemId}`}><input className="form-control" id={`item-discount-${value.itemId}`} type="number" min={0} step="0.01" value={value.discountAmount} onChange={(event) => setValues((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, discountAmount: event.target.value } : item))} disabled={isSaving} /></FormField></div>)}<div className="quote-editor-fields"><FormField label="Descuento general" htmlFor="quote-general-discount"><input className="form-control" id="quote-general-discount" type="number" min={0} step="0.01" value={generalDiscount} onChange={(event) => setGeneralDiscount(event.target.value)} disabled={isSaving} /></FormField><FormField label="IGV (%)" htmlFor="quote-tax-rate"><input className="form-control" id="quote-tax-rate" type="number" min={0} max={100} step="0.01" value={tax} onChange={(event) => setTax(event.target.value)} disabled={isSaving} /></FormField></div><Button type="button" isLoading={isSaving} onClick={() => onSave({ items: values.map((item) => ({ itemId: item.itemId, unitPrice: Number(item.unitPrice), discountAmount: Number(item.discountAmount) })), discountAmount: Number(generalDiscount), taxRate: Number(tax) })}>Guardar pricing</Button></section>;
}
