import PDFDocument from "pdfkit";
import type { QuoteDocumentData } from "../quoteDocument.types.js";

const RED = "#c8102e";
const NAVY = "#172536";
const TEXT = "#30343b";
const MUTED = "#6c737d";
const BORDER = "#d8dce2";
const MARGIN = 50;

function date(value: Date | string): string { const parsed = value instanceof Date ? value : new Date(`${value}T12:00:00`); return new Intl.DateTimeFormat("es-PE", { dateStyle: "long", timeZone: "America/Lima" }).format(parsed); }
function money(value: number, currency: string): string { return new Intl.NumberFormat("es-PE", { style: "currency", currency, minimumFractionDigits: 2 }).format(value); }
function line(doc: PDFKit.PDFDocument): void { doc.strokeColor(BORDER).lineWidth(.7).moveTo(MARGIN, doc.y).lineTo(doc.page.width - MARGIN, doc.y).stroke(); }
function space(doc: PDFKit.PDFDocument, height: number): void { if (doc.y + height > doc.page.height - 70) { doc.addPage(); doc.y = MARGIN; } }
function header(doc: PDFKit.PDFDocument, data: QuoteDocumentData): void { doc.rect(0, 0, 8, 105).fill(RED); doc.fillColor(RED).font("Helvetica-Bold").fontSize(25).text("ISOCAL", MARGIN, 42); doc.fillColor(MUTED).font("Helvetica").fontSize(8.5).text("Mediciones que mejoran decisiones", MARGIN, 72); doc.fillColor(TEXT).font("Helvetica-Bold").fontSize(8.5).text(data.company.legalName, 315, 40, { width: 230, align: "right" }); doc.fillColor(MUTED).font("Helvetica").fontSize(8).text(`RUC: ${data.company.ruc}`, 315, 54, { width: 230, align: "right" }).text(data.company.email, { width: 230, align: "right" }).text(data.company.phone, { width: 230, align: "right" }).text(data.company.website, { width: 230, align: "right" }); if (data.company.address) doc.text(data.company.address, { width: 230, align: "right" }); doc.y = 125; line(doc); doc.y = 145; }
function title(doc: PDFKit.PDFDocument, data: QuoteDocumentData): void { doc.fillColor(NAVY).font("Helvetica-Bold").fontSize(24).text("Cotización"); doc.fillColor(RED).fontSize(12).text(data.reference, { align: "right" }); doc.moveDown(1); doc.fillColor(MUTED).fontSize(8).text(`Fecha de emisión: ${date(data.issuedAt)}`); doc.text(`Válida hasta: ${date(data.validUntil)}`); doc.moveDown(1); }
function customer(doc: PDFKit.PDFDocument, data: QuoteDocumentData): void { doc.fillColor(RED).font("Helvetica-Bold").fontSize(8).text("CLIENTE"); doc.fillColor(NAVY).fontSize(14).text(data.customer.companyName ?? data.customer.name); doc.fillColor(TEXT).font("Helvetica").fontSize(9); if (data.customer.companyName) doc.text(`Contacto: ${data.customer.name}`); if (data.customer.ruc) doc.text(`RUC: ${data.customer.ruc}`); doc.text(`Correo: ${data.customer.email}`).text(`Teléfono: ${data.customer.phone}`); doc.moveDown(1); }
function products(doc: PDFKit.PDFDocument, data: QuoteDocumentData): void { space(doc, 45); const y = doc.y; doc.rect(MARGIN, y, 495, 24).fill(NAVY); doc.fillColor("#fff").font("Helvetica-Bold").fontSize(7.5).text("DESCRIPCIÓN", 58, y + 8).text("CANT.", 265, y + 8, { width: 38, align: "center" }).text("P. UNIT.", 310, y + 8, { width: 70, align: "right" }).text("DSCTO.", 386, y + 8, { width: 65, align: "right" }).text("SUBTOTAL", 456, y + 8, { width: 80, align: "right" }); doc.y = y + 30; for (const item of data.items) { const itemHeight = Math.max(35, doc.heightOfString(item.productName, { width: 195 }) + (item.customerNotes ? doc.heightOfString(item.customerNotes, { width: 195 }) + 5 : 0) + 15); space(doc, itemHeight); const rowY = doc.y; doc.strokeColor(BORDER).rect(MARGIN, rowY, 495, itemHeight).stroke(); doc.fillColor(TEXT).font("Helvetica-Bold").fontSize(8.5).text(item.productName, 58, rowY + 8, { width: 195 }); if (item.customerNotes) doc.fillColor(MUTED).font("Helvetica").fontSize(7.5).text(item.customerNotes, 58, rowY + 22, { width: 195 }); doc.fillColor(TEXT).font("Helvetica").fontSize(8.5).text(String(item.quantity), 265, rowY + 10, { width: 38, align: "center" }).text(money(item.unitPrice, data.currency), 310, rowY + 10, { width: 70, align: "right" }).text(money(item.discountAmount, data.currency), 386, rowY + 10, { width: 65, align: "right" }).font("Helvetica-Bold").text(money(item.subtotal, data.currency), 456, rowY + 10, { width: 80, align: "right" }); doc.y = rowY + itemHeight; } doc.moveDown(1); }
function financial(doc: PDFKit.PDFDocument, data: QuoteDocumentData): void { space(doc, 150); const x = doc.page.width - MARGIN - 240; let y = doc.y; const rows = [["Subtotal", money(data.financial.grossSubtotal, data.currency)], ["Descuentos", `- ${money(data.financial.totalDiscountAmount, data.currency)}`], ["Base imponible", money(data.financial.taxableSubtotal, data.currency)], [`IGV (${data.financial.taxRate}%)`, money(data.financial.taxAmount, data.currency)]]; for (const [label, value] of rows) { doc.fillColor(MUTED).font("Helvetica").fontSize(8.5).text(label, x, y, { width: 105 }); doc.fillColor(TEXT).font("Helvetica-Bold").text(value, x + 110, y, { width: 130, align: "right" }); y += 22; } doc.rect(x, y, 240, 38).fill(NAVY); doc.fillColor("#fff").font("Helvetica-Bold").fontSize(10).text("TOTAL", x + 12, y + 13).fontSize(13).text(money(data.financial.total, data.currency), x + 90, y + 11, { width: 138, align: "right" }); doc.y = y + 58; }
function commercial(doc: PDFKit.PDFDocument, data: QuoteDocumentData): void { space(doc, 100); line(doc); doc.moveDown(1); doc.fillColor(RED).font("Helvetica-Bold").fontSize(8).text("CONDICIONES COMERCIALES"); doc.moveDown(.4); doc.fillColor(TEXT).font("Helvetica-Bold").fontSize(9).text("Condiciones de pago"); doc.fillColor(MUTED).font("Helvetica").text(data.paymentTerms); doc.moveDown(.6).fillColor(TEXT).font("Helvetica-Bold").text("Vigencia"); doc.fillColor(MUTED).font("Helvetica").text(`Hasta ${date(data.validUntil)}`); if (data.commercialNotes) { doc.moveDown(.6).fillColor(TEXT).font("Helvetica-Bold").text("Observaciones"); doc.fillColor(MUTED).font("Helvetica").text(data.commercialNotes); } }
export function renderQuoteDocument(data: QuoteDocumentData): Promise<Buffer> { return new Promise((resolve, reject) => { const doc = new PDFDocument({ size: "A4", margins: { top: MARGIN, right: MARGIN, bottom: 70, left: MARGIN }, bufferPages: true, info: { Title: `Cotización ${data.reference}`, Author: "ISOCAL" } }); const chunks: Buffer[] = []; doc.on("data", (chunk: Buffer) => chunks.push(Buffer.from(chunk))); doc.on("end", () => resolve(Buffer.concat(chunks))); doc.on("error", reject); header(doc, data); title(doc, data); customer(doc, data); products(doc, data); financial(doc, data); commercial(doc, data); const pages = doc.bufferedPageRange(); for (let page = pages.start; page < pages.start + pages.count; page += 1) { doc.switchToPage(page); doc.fillColor(MUTED).font("Helvetica").fontSize(7).text(`${data.reference} · Página ${page - pages.start + 1} de ${pages.count}`, MARGIN, doc.page.height - 38, { width: doc.page.width - MARGIN * 2, align: "center" }); } doc.end(); }); }
